[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd legaleasy/web && npm install"]

[phases.build]
cmds = ["echo 'No build needed'"]

[start]
cmd = "cd legaleasy/web && npm start"
