[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd legaleasy/web && npm install"]

[phases.build]
cmds = ["cd legaleasy/web/frontend && npm install && npm run build"]

[start]
cmd = "cd legaleasy/web && npm start"
