# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5726c676e712cb30ecfd34bb2064746a"
name = "legaleasy"
application_url = "https://pointed-here-moms-ministries.trycloudflare.com"
embedded = true
handle = "legaleasy-2"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://pointed-here-moms-ministries.trycloudflare.com/auth/callback", "https://pointed-here-moms-ministries.trycloudflare.com/auth/shopify/callback", "https://pointed-here-moms-ministries.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
