# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "92e0255bdd192b7db878b91a82e4e383"
name = "Legal Easy"
application_url = "https://t-c-widget-production.up.railway.app"
embedded = true
handle = "legal-easy"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[webhooks.privacy_compliance]
customer_data_request_url = "https://t-c-widget-production.up.railway.app/api/webhooks"
customer_deletion_url = "https://t-c-widget-production.up.railway.app/api/webhooks"
shop_deletion_url = "https://t-c-widget-production.up.railway.app/api/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://t-c-widget-production.up.railway.app/api/auth/callback"
]

[app_proxy]
url = "https://t-c-widget-production.up.railway.app"
subpath = "legaleasy"
prefix = "apps"

[pos]
embedded = false
